CREATE TABLE IF NOT EXISTS IDN_RULE (
	UUID CHAR(36) NOT NULL,
	RULE BLOB NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	TENANT_ID INTEGER NOT NULL,
	PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS IDN_RULE_REFERENCES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
	RULE_UUID CHAR(36) NOT NULL,
	FIELD_NAME VARCHAR(100) NOT NULL,
	FIELD_REFERENCE VARCHAR(255) NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (RULE_UUID) REFERENCES IDN_RULE(UUID) ON DELETE CASCADE
);
