CREATE TABLE IF NOT EXISTS IDN_RULE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
	UUID CHAR(36) NOT NULL,
	CONTENT BLOB NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	TENANT_ID INTEGER NOT NULL,
	VERSION VARCHAR(15) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (UUID)
);

CREATE TABLE IF NOT EXISTS IDN_RULE_REFERENCES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
	RULE_ID INTEGER NOT NULL,
	FIELD_NAME VARCHAR(100) NOT NULL,
	FIELD_REFERENCE VARCHAR(255) NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (RULE_ID) REFERENCES IDN_RULE(ID) ON DELETE CASCADE
);
