CREATE TABLE IF NOT EXISTS IDN_POLICY (
    ID          CHAR(36)      NOT NULL,
    POLICY_NAME VARCHAR(255)  NOT NULL,
    TENANT_ID   INTEGER       NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (POLICY_NAME, TENANT_ID)
);

CREATE TABLE IF NOT EXISTS IDN_POLICY_RULE (
    ID          CHAR(36)      NOT NULL,
    POLICY_ID   CHAR(36)      NOT NULL,
    RULE_ID     CHAR(36)      NOT NULL,
    PLATFORM    VARCHAR(50)   NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (POLICY_ID) REFERENCES IDN_POLICY (ID) ON DELETE CASCADE
);

