CREATE TABLE IF NOT EXISTS IDN_DEVICE_TOKEN_JTI (
    JTI             VARCHAR(255)  NOT NULL,
    TENANT_ID       INTEGER       NOT NULL,
    IAT             TIMESTAMP     NOT NULL,
    EXPIRY_TIME     TIMESTAMP     NOT NULL,
    PRIMARY KEY (TENANT_ID, JTI)
);

CREATE INDEX IDX_IDN_DEVICE_TOKEN_JTI_EXPIRY ON IDN_DEVICE_TOKEN_JTI (EXPIRY_TIME);
