-- Table: IDN_WEBHOOKS
CREATE TABLE IF NOT EXISTS IDN_WEBHOOKS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(2048) NOT NULL,
    ENDPOINT VARCHAR(2048) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    SECRET VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(32) NOT NULL,
    EVENT_SCHEMA_NAME VARCHAR(64) NOT NULL,
    EVENT_SCHEMA_URI VARCHAR(255) NOT NULL,
    EVENT_SCHEMA_VERSION VARCHAR(32) NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_IDN_WEBHOOKS_UUID UNIQUE(UUID),
    CONSTRAINT UQ_IDN_WEBHOOKS_TENANT_ENDPOINT UNIQUE(TENANT_ID, ENDPOINT)
    );

-- Table: IDN_WEBHOOK_EVENTS
CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_EVENTS (
    WEBHOOK_ID INTEGER NOT NULL,
    EVENT_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (WEBHOOK_ID, EVENT_NAME),
    CONSTRAINT FK_IDN_WEBHOOK_EVENTS_WEBHOOKS
    FOREIGN KEY (WEBHOOK_ID)
    REFERENCES IDN_WEBHOOKS(ID)
    ON DELETE CASCADE
    );

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOKS_TENANT ON IDN_WEBHOOKS(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOKS_UUID ON IDN_WEBHOOKS(UUID);
