CREATE OR REPLACE PROCEDURE WSO2_VC_NONCE_CLEANUP

BEGIN

-- ------------------------------------------
-- DECLARE VARIABLES
-- ------------------------------------------
DECLARE batchSize INT;
DECLARE chunkSize INT;
DECLARE batchCount INT;
DECLARE chunkCount INT;
DECLARE rowCount INT;
DECLARE v_rowCount INT;
DECLARE enableLog SMALLINT;
DECLARE backupTables SMALLINT;
DECLARE cleanUpDateTimeLimit TIMESTAMP;

-- ------------------------------------------
-- CONFIGURABLE VARIABLES
-- ------------------------------------------
SET batchSize = 10000; -- SET BATCH SIZE FOR AVOID TABLE LOCKS [DEFAULT : 10000]
SET chunkSize = 500000; -- CHUNK WISE DELETE FOR LARGE TABLES [DEFAULT : 500000]
SET enableLog = 0; -- ENABLE LOGGING [DEFAULT : 0]
SET backupTables = 0; -- SET IF VC NONCE TABLE NEEDS TO BE BACKED-UP BEFORE DELETE [DEFAULT : 0]

SET rowCount = 0;
SET batchCount = 1;
SET chunkCount = 1;
SET cleanUpDateTimeLimit = CURRENT TIMESTAMP - CURRENT TIMEZONE;

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('WSO2_VC_NONCE_CLEANUP() STARTED...!');
END IF;

-- ------------------------------------------
-- BACKUP DATA
-- ------------------------------------------
IF (backupTables = 1) THEN
    IF (enableLog = 1) THEN
        CALL DBMS_OUTPUT.PUT_LINE('TABLE BACKUP STARTED...!');
    END IF;

    IF (EXISTS (SELECT NAME FROM SYSIBM.SYSTABLES WHERE NAME = 'BAK_IDN_VC_NONCE')) THEN
        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('DELETING OLD BACKUP...');
        END IF;
        DROP TABLE BAK_IDN_VC_NONCE;
    END IF;

    CREATE TABLE BAK_IDN_VC_NONCE AS (SELECT * FROM IDN_VC_NONCE) WITH DATA;
END IF;

-- ------------------------------------------
-- CLEANUP DATA
-- ------------------------------------------
NONCE_CHUNK_LOOP:
WHILE (chunkCount > 0) DO

    -- CREATE CHUNK TABLE
    DROP TABLE IF EXISTS IDN_VC_NONCE_CHUNK_TMP;
    CREATE TABLE IDN_VC_NONCE_CHUNK_TMP AS (SELECT TENANT_ID, NONCE FROM IDN_VC_NONCE) WITH NO DATA;

    INSERT INTO IDN_VC_NONCE_CHUNK_TMP
    SELECT TENANT_ID, NONCE
    FROM IDN_VC_NONCE
    WHERE EXPIRY_TIME < cleanUpDateTimeLimit
    LIMIT chunkSize;

    GET DIAGNOSTICS v_rowCount = ROW_COUNT;
    SET chunkCount = v_rowCount;

    IF (chunkCount = 0) THEN
        LEAVE NONCE_CHUNK_LOOP;
    END IF;

    CREATE INDEX IDN_VC_NONCE_CHUNK_TMP_INDX ON IDN_VC_NONCE_CHUNK_TMP (TENANT_ID, NONCE);

    IF (enableLog = 1) THEN
        CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_VC_NONCE_CHUNK_TMP...');
    END IF;

    -- BATCH LOOP
    SET batchCount = 1;
    NONCE_BATCH_LOOP:
    WHILE (batchCount > 0) DO

        -- CREATE BATCH TABLE
        DROP TABLE IF EXISTS IDN_VC_NONCE_BATCH_TMP;
        CREATE TABLE IDN_VC_NONCE_BATCH_TMP(TENANT_ID INTEGER, NONCE VARCHAR(255));

        INSERT INTO IDN_VC_NONCE_BATCH_TMP
        SELECT TENANT_ID, NONCE
        FROM IDN_VC_NONCE_CHUNK_TMP
        LIMIT batchSize;

        GET DIAGNOSTICS v_rowCount = ROW_COUNT;
        SET batchCount = v_rowCount;

        IF (batchCount = 0) THEN
            LEAVE NONCE_BATCH_LOOP;
        END IF;

        CREATE INDEX IDN_VC_NONCE_BATCH_TMP_INDX ON IDN_VC_NONCE_BATCH_TMP (TENANT_ID, NONCE);

        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_VC_NONCE_BATCH_TMP...');
        END IF;

        -- BATCH DELETION
        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('BATCH DELETE STARTED ON IDN_VC_NONCE...');
        END IF;

        DELETE FROM IDN_VC_NONCE
        WHERE EXISTS (
            SELECT 1
            FROM IDN_VC_NONCE_BATCH_TMP
            WHERE IDN_VC_NONCE.TENANT_ID = IDN_VC_NONCE_BATCH_TMP.TENANT_ID
              AND IDN_VC_NONCE.NONCE = IDN_VC_NONCE_BATCH_TMP.NONCE
        );

        GET DIAGNOSTICS rowCount = ROW_COUNT;

        -- DELETE FROM CHUNK
        DELETE FROM IDN_VC_NONCE_CHUNK_TMP
        WHERE EXISTS (
            SELECT 1
            FROM IDN_VC_NONCE_BATCH_TMP
            WHERE IDN_VC_NONCE_CHUNK_TMP.TENANT_ID = IDN_VC_NONCE_BATCH_TMP.TENANT_ID
              AND IDN_VC_NONCE_CHUNK_TMP.NONCE = IDN_VC_NONCE_BATCH_TMP.NONCE
        );
    END WHILE;
END WHILE;

-- DELETE TEMP TABLES
DROP TABLE IF EXISTS IDN_VC_NONCE_BATCH_TMP;
DROP TABLE IF EXISTS IDN_VC_NONCE_CHUNK_TMP;

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('CLEANUP COMPLETED...!');
END IF;

END/
