/*
 * Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.role.v2.mgt.core.dao;

/**
 * SQL Queries used in {@link RoleDAOImpl}.
 */
public class SQLQueries {

    public static final String ADD_ROLE_WITH_AUDIENCE_SQL = "INSERT INTO UM_HYBRID_ROLE (UM_ROLE_NAME, " +
            "AUDIENCE_REF_ID, UM_TENANT_ID) VALUES (:UM_ROLE_NAME;, :AUDIENCE_REF_ID;, :UM_TENANT_ID;)";

    public static final String ADD_ROLE_AUDIENCE_SQL = "INSERT INTO UM_HYBRID_ROLE_AUDIENCE (AUDIENCE,AUDIENCE_ID) " +
            "VALUES (:AUDIENCE;, :AUDIENCE_ID;)";

    public static final String GET_ROLE_AUDIENCE_SQL = "SELECT ID FROM UM_HYBRID_ROLE_AUDIENCE WHERE AUDIENCE " +
            "=:AUDIENCE; AND AUDIENCE_ID=:AUDIENCE_ID;";

    public static final String ADD_ROLE_SCOPE_SQL = "INSERT INTO ROLE_SCOPE (ROLE_ID, SCOPE_NAME, TENANT_ID) VALUES " +
            "(:ROLE_ID;, :SCOPE_NAME;, :TENANT_ID;)";

    public static final String DELETE_ROLE_SCOPE_BY_SCOPE_NAME_SQL = "DELETE ROLE_SCOPE WHERE ROLE_ID =:ROLE_ID; AND " +
            "SCOPE_NAME=:SCOPE_NAME;";

    public static final String DELETE_ROLE_SCOPE_BY_ROLE_ID_SQL = "DELETE ROLE_SCOPE WHERE ROLE_ID =:ROLE_ID;";

    public static final String GET_ROLE_SCOPE_SQL = "SELECT NAME, DISPLAY_NAME FROM ROLE_SCOPE INNER JOIN SCOPE ON " +
            "ROLE_SCOPE.SCOPE_NAME = SCOPE.NAME WHERE ROLE_ID =:ROLE_ID; AND ROLE_SCOPE.TENANT_ID =:TENANT_ID;";

    public static final String GET_ASSOCIATED_APPS_BY_ROLE_ID_SQL = "SELECT APP_ID, APP_NAME FROM " +
            "APP_ROLE_ASSOCIATION INNER JOIN SP_APP ON APP_ROLE_ASSOCIATION.APP_ID = SP_APP.UUID " +
            "WHERE ROLE_ID =:ROLE_ID;";
    public static final String DELETE_APP_ROLE_ASSOCIATION_BY_ROLE_ID_SQL = "DELETE APP_ROLE_ASSOCIATION WHERE " +
            "ROLE_ID=:ROLE_ID;";

    public static final String IS_SHARED_ROLE_SQL = "SELECT COUNT(MAIN_ROLE_ID) FROM UM_SHARED_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE ON UM_SHARED_ROLE.SHARED_ROLE_ID = UM_HYBRID_ROLE.UM_ID WHERE UM_ROLE_NAME "
            + "=:ROLE_NAME; AND SHARED_ROLE_TENANT_ID=:SHARED_ROLE_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";
    public static final String GET_SHARED_ROLE_MAIN_ROLE_ID_SQL = "SELECT UM_ROLE_NAME, MAIN_ROLE_TENANT_ID, " +
            "AUDIENCE_REF_ID FROM UM_SHARED_ROLE INNER JOIN UM_HYBRID_ROLE ON UM_SHARED_ROLE.SHARED_ROLE_ID = " +
            "UM_HYBRID_ROLE.UM_ID WHERE UM_ROLE_NAME =:ROLE_NAME; AND SHARED_ROLE_TENANT_ID=:SHARED_ROLE_TENANT_ID; " +
            "AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";
    public static final String IS_ROLE_EXIST_SQL = "SELECT COUNT(UM_ID) FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME "
            + "=:UM_ROLE_NAME; AND UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";

    public static final String GET_ROLE_ID_BY_NAME_AND_AUDIENCE_SQL = "SELECT ATTR_VALUE FROM IDN_SCIM_GROUP WHERE "
            + "TENANT_ID=:TENANT_ID; AND ROLE_NAME=:ROLE_NAME; AND ATTR_NAME=:ATTR_NAME; AND " +
            "AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";
    public static final String ADD_USER_TO_ROLE_SQL = "INSERT INTO UM_HYBRID_USER_ROLE (UM_USER_NAME, UM_ROLE_ID, "
            + "UM_TENANT_ID, UM_DOMAIN_ID) VALUES (:UM_USER_NAME;,(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE "
            + "UM_ROLE_NAME=:UM_ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID; AND UM_TENANT_ID=:UM_TENANT_ID;), " +
            ":UM_TENANT_ID;, (SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE UM_TENANT_ID=:UM_TENANT_ID; AND " +
            "UM_DOMAIN_NAME=:UM_DOMAIN_NAME;))";

    public static final String ADD_USER_TO_ROLE_SQL_MSSQL = "INSERT INTO UM_HYBRID_USER_ROLE (UM_USER_NAME, " +
            "UM_ROLE_ID, UM_TENANT_ID,  UM_DOMAIN_ID) SELECT (:UM_USER_NAME;),(SELECT UM_ID FROM UM_HYBRID_ROLE " +
            "WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID; AND " +
            "UM_TENANT_ID=:UM_TENANT_ID;), (:UM_TENANT_ID;), (SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND UM_DOMAIN_NAME=:UM_DOMAIN_NAME;)";

    public static final String ADD_GROUP_TO_ROLE_SQL = "INSERT INTO UM_HYBRID_GROUP_ROLE (UM_GROUP_NAME, UM_ROLE_ID, "
            + "UM_TENANT_ID, UM_DOMAIN_ID) VALUES (:UM_GROUP_NAME;,(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE "
            + "UM_ROLE_NAME=:UM_ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID; AND UM_TENANT_ID=:UM_TENANT_ID;), " +
            ":UM_TENANT_ID;, (SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE UM_TENANT_ID=:UM_TENANT_ID; AND " +
            "UM_DOMAIN_NAME=:UM_DOMAIN_NAME;))";

    public static final String ADD_GROUP_TO_ROLE_SQL_MSSQL = "INSERT INTO UM_HYBRID_GROUP_ROLE (UM_GROUP_NAME, " +
            "UM_ROLE_ID, UM_TENANT_ID,  UM_DOMAIN_ID) SELECT (:UM_GROUP_NAME;),(SELECT UM_ID FROM UM_HYBRID_ROLE " +
            "WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID; AND " +
            "UM_TENANT_ID=:UM_TENANT_ID;), (:UM_TENANT_ID;), (SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND UM_DOMAIN_NAME=:UM_DOMAIN_NAME;)";

    public static final String ADD_SCIM_ROLE_ID_SQL = "INSERT INTO IDN_SCIM_GROUP (TENANT_ID, ROLE_NAME, ATTR_NAME, " +
            "ATTR_VALUE, AUDIENCE_REF_ID) VALUES (:TENANT_ID;, :ROLE_NAME;, :ATTR_NAME;, :ATTR_VALUE;, " +
            ":AUDIENCE_REF_ID;)";

    public static final String GET_AUDIENCE_BY_ID_SQL = "SELECT AUDIENCE, AUDIENCE_ID FROM UM_HYBRID_ROLE_AUDIENCE " +
            "WHERE ID=:AUDIENCE_REF_ID;";

    public static final String GET_AUDIENCE_REF_BY_ID_SQL = "SELECT AUDIENCE_REF_ID FROM IDN_SCIM_GROUP WHERE " +
            "TENANT_ID=:TENANT_ID; AND ATTR_NAME=:ATTR_NAME; AND ATTR_VALUE=:ATTR_VALUE;";

    public static final String ADD_IDP_GROUPS_SQL = "INSERT INTO UM_IDP_GROUP_ROLE (ROLE_ID, GROUP_ID, UM_TENANT_ID) " +
            "VALUES ((SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;), :GROUP_ID;, :UM_TENANT_ID;)";
    public static final String DELETE_IDP_GROUPS_SQL = "DELETE UM_IDP_GROUP_ROLE WHERE GROUP_ID=:GROUP_ID; AND " +
            "ROLE_ID=(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;) AND UM_TENANT_ID=:UM_TENANT_ID;";

    public static final String GET_IDP_GROUPS_SQL = "SELECT GROUP_ID FROM UM_IDP_GROUP_ROLE WHERE " +
            "ROLE_ID=(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;) AND UM_TENANT_ID=:UM_TENANT_ID;";

    public static final String UPDATE_ROLE_NAME_SQL = "UPDATE UM_HYBRID_ROLE SET UM_ROLE_NAME=:NEW_UM_ROLE_NAME; " +
            "WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";

    public static final String UPDATE_SCIM_ROLE_NAME_SQL = "UPDATE IDN_SCIM_GROUP SET ROLE_NAME=:NEW_ROLE_NAME; " +
            "WHERE TENANT_ID=:TENANT_ID; AND ROLE_NAME=:ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";

    public static final String GET_USER_LIST_OF_ROLE_SQL = "SELECT UM_USER_NAME, UM_DOMAIN_NAME FROM " +
            "UM_HYBRID_USER_ROLE, UM_DOMAIN WHERE UM_ROLE_ID=(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE " +
            "UM_ROLE_NAME=:UM_ROLE_NAME; AND UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;) " +
            "AND UM_HYBRID_USER_ROLE.UM_TENANT_ID=:UM_TENANT_ID; AND " +
            "UM_HYBRID_USER_ROLE.UM_DOMAIN_ID=UM_DOMAIN.UM_DOMAIN_ID";

    public static final String DELETE_ROLE_SQL = "DELETE FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND "
            + "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";

    public static final String DELETE_SCIM_ROLE_SQL = "DELETE FROM IDN_SCIM_GROUP WHERE TENANT_ID=:TENANT_ID; AND "
            + "ROLE_NAME=:ROLE_NAME; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;";

    public static final String GET_GROUP_LIST_OF_ROLE_SQL = "SELECT UM_GROUP_NAME, UM_DOMAIN_NAME FROM " +
            "UM_HYBRID_GROUP_ROLE, UM_DOMAIN WHERE UM_ROLE_ID=(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE " +
            "UM_ROLE_NAME=:UM_ROLE_NAME; AND UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;) AND " +
            "UM_HYBRID_GROUP_ROLE.UM_TENANT_ID=:UM_TENANT_ID; AND " +
            "UM_HYBRID_GROUP_ROLE.UM_DOMAIN_ID=UM_DOMAIN.UM_DOMAIN_ID";

    public static final String GET_ROLE_NAME_BY_ID_SQL = "SELECT ROLE_NAME FROM IDN_SCIM_GROUP WHERE "
            + "TENANT_ID=:TENANT_ID; AND ATTR_NAME=:ATTR_NAME; AND ATTR_VALUE=:ATTR_VALUE;";

    public static final String IS_ROLE_ID_EXIST_SQL = "SELECT COUNT(ID) FROM IDN_SCIM_GROUP WHERE "
            + "TENANT_ID=:TENANT_ID; AND ATTR_NAME=:ATTR_NAME; AND ATTR_VALUE=:ATTR_VALUE;";

    public static final String REMOVE_GROUP_FROM_ROLE_SQL =
            "DELETE FROM UM_HYBRID_GROUP_ROLE WHERE " + "UM_GROUP_NAME=:UM_GROUP_NAME; AND "
                    + "UM_ROLE_ID=(SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=:UM_ROLE_NAME; AND "
                    + "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID=:AUDIENCE_REF_ID;) AND " +
                    "UM_TENANT_ID=:UM_TENANT_ID; AND UM_DOMAIN_ID=(SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE "
                    + "UM_TENANT_ID=:UM_TENANT_ID; AND UM_DOMAIN_NAME=:UM_DOMAIN_NAME;)";

    public static final String COUNT_ROLES_BY_TENANT_MYSQL = "SELECT COUNT(UM_ROLE_NAME) FROM UM_HYBRID_ROLE WHERE "
            + "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1";

    public static final String COUNT_ROLES_BY_TENANT_ORACLE = "SELECT COUNT(UM_ROLE_NAME) FROM (SELECT UM_ROLE_NAME, "
            + "rownum AS rnum FROM (SELECT UM_ROLE_NAME FROM UM_HYBRID_ROLE WHERE UM_TENANT_ID=:UM_TENANT_ID; AND " +
            "AUDIENCE_REF_ID != -1))";

    public static final String COUNT_ROLES_BY_TENANT_MSSQL = "SELECT COUNT(UM_ROLE_NAME) FROM UM_HYBRID_ROLE WHERE "
            + "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1";

    public static final String COUNT_ROLES_BY_TENANT_POSTGRESQL = "SELECT COUNT(UM_ROLE_NAME) FROM UM_HYBRID_ROLE "
            + "WHERE UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1";

    public static final String COUNT_ROLES_BY_TENANT_DB2 = "SELECT COUNT(UM_ROLE_NAME) FROM (SELECT ROW_NUMBER() "
            + "OVER(ORDER BY UM_ID DESC) AS rn,UM_HYBRID_ROLE.* FROM UM_HYBRID_ROLE WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1)";

    public static final String COUNT_ROLES_BY_TENANT_INFORMIX = "SELECT COUNT(UM_ROLE_NAME) FROM UM_HYBRID_ROLE WHERE"
            + " UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1";

    // DB queries to list roles.
    public static final String GET_ROLES_BY_TENANT_MYSQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY UM_ID DESC LIMIT :OFFSET;, :LIMIT;";

    public static final String GET_ROLES_BY_TENANT_ORACLE = "SELECT UM_ROLE_NAME, AUDIENCE, AUDIENCE_ID, " +
            "AUDIENCE_REF_ID FROM (SELECT UM_ROLE_NAME, AUDIENCE, AUDIENCE_ID, AUDIENCE_REF_ID, rownum AS rnum " +
            "FROM (SELECT UM_ROLE_NAME, AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM " +
            "UM_HYBRID_ROLE INNER JOIN UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = " +
            "UM_HYBRID_ROLE_AUDIENCE.ID WHERE UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY " +
            "UM_ID DESC) WHERE rownum <= :END_INDEX;) WHERE rnum > :ZERO_BASED_START_INDEX;";

    public static final String GET_ROLES_BY_TENANT_MSSQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY UM_ID DESC OFFSET :OFFSET; ROWS FETCH " +
            "NEXT :LIMIT; ROWS ONLY";

    public static final String GET_ROLES_BY_TENANT_POSTGRESQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY UM_ID DESC LIMIT :LIMIT; OFFSET :OFFSET;";

    public static final String GET_ROLES_BY_TENANT_DB2 = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM (SELECT ROW_NUMBER() " +
            "OVER(ORDER BY UM_ID DESC) AS rn, UM_HYBRID_ROLE.* FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1) WHERE rn BETWEEN :ONE_BASED_START_INDEX; " +
            "AND :END_INDEX;";

    public static final String GET_ROLES_BY_TENANT_INFORMIX = "SELECT SKIP :OFFSET; FIRST :LIMIT; UM_ROLE_NAME, " +
            "AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY UM_ID DESC";

    // DB queries to filter roles.
    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_MYSQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 AND UM_ROLE_NAME LIKE :UM_ROLE_NAME; ORDER BY " +
            "UM_ID DESC LIMIT :OFFSET;, :LIMIT;";

    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_ORACLE = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "AUDIENCE_ID, AUDIENCE_REF_ID FROM (SELECT UM_ROLE_NAME, AUDIENCE, AUDIENCE_ID, AUDIENCE_REF_ID, rownum " +
            "AS rnum FROM (SELECT UM_ROLE_NAME, AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID " +
            "FROM UM_HYBRID_ROLE INNER JOIN UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = " +
            "UM_HYBRID_ROLE_AUDIENCE.ID WHERE UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 ORDER BY " +
            "UM_ID DESC) WHERE UM_ROLE_NAME LIKE :UM_ROLE_NAME; AND rownum <= :END_INDEX;) WHERE rnum > " +
            ":ZERO_BASED_START_INDEX;";

    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_MSSQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 AND UM_ROLE_NAME LIKE :UM_ROLE_NAME; ORDER BY " +
            "UM_ID DESC OFFSET :OFFSET; ROWS FETCH NEXT :LIMIT; ROWS ONLY";

    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_POSTGRESQL = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 AND UM_ROLE_NAME LIKE :UM_ROLE_NAME; ORDER BY " +
            "UM_ID DESC LIMIT :LIMIT; OFFSET :OFFSET;";

    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_DB2 = "SELECT UM_ROLE_NAME, AUDIENCE, " +
            "UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM (SELECT ROW_NUMBER() " +
            "OVER(ORDER BY UM_ID DESC) AS rn, UM_HYBRID_ROLE.* FROM UM_HYBRID_ROLE INNER JOIN " +
            "UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 AND UM_ROLE_NAME LIKE :UM_ROLE_NAME;) WHERE " +
            "rn BETWEEN :ONE_BASED_START_INDEX; AND :END_INDEX;";

    public static final String GET_ROLES_BY_TENANT_AND_ROLE_NAME_INFORMIX = "SELECT SKIP :OFFSET; FIRST :LIMIT; " +
            "UM_ROLE_NAME, AUDIENCE, UM_HYBRID_ROLE_AUDIENCE.AUDIENCE_ID, AUDIENCE_REF_ID FROM UM_HYBRID_ROLE INNER " +
            "JOIN UM_HYBRID_ROLE_AUDIENCE ON UM_HYBRID_ROLE.AUDIENCE_REF_ID = UM_HYBRID_ROLE_AUDIENCE.ID WHERE " +
            "UM_TENANT_ID=:UM_TENANT_ID; AND AUDIENCE_REF_ID != -1 AND UM_ROLE_NAME LIKE :UM_ROLE_NAME; ORDER BY " +
            "UM_ID DESC";

    // Groups related queries.
    public static final String GET_GROUP_NAME_BY_ID_SQL = "SELECT ROLE_NAME FROM IDN_SCIM_GROUP WHERE "
            + "TENANT_ID=:TENANT_ID; AND ATTR_NAME=:ATTR_NAME; AND ATTR_VALUE=:ATTR_VALUE;";

    public static final String GET_GROUP_ID_BY_NAME_SQL = "SELECT ATTR_VALUE FROM IDN_SCIM_GROUP WHERE "
            + "TENANT_ID=:TENANT_ID; AND ROLE_NAME=:ROLE_NAME; AND ATTR_NAME=:ATTR_NAME;";

}
