/*
 * Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.claim.mgt.dao;


public class ClaimDBConstants {

    public static final String ADD_DIALECT_SQL = "INSERT INTO IDN_DIALECT (IDN_DIALECT_URI, " +
            "IDN_TENANT_ID) VALUES (?, ?)";
    public static final String ADD_CLAIM_SQL = "INSERT INTO IDN_CLAIM(IDN_DIALECT_ID, IDN_CLAIM_URI, " +
            "IDN_TENANT_ID) VALUES (?,?,?)";

    public static final String DELETE_CLAIM_SQL = "DELETE FROM IDN_CLAIM WHERE IDN_CLAIM_URI=? AND " +
            "IDN_DIALECT_ID=(SELECT IDN_ID FROM IDN_DIALECT WHERE IDN_DIALECT_URI=? " +
            "AND IDN_TENANT_ID=?) AND IDN_TENANT_ID=?";

    public static final String DELETE_CLAIM_RELATION_SQL = "DELETE FROM IDN_CLAIM_MAPPING WHERE " +
            "IDN_LOCAL_CLAIM_ID=? OR IDN_ADDITIONAL_CLAIM_ID=? AND IDN_TENANT_ID=?";

    public static final String DELETE_CLAIM_META_DATA_SQL = "DELETE FROM IDN_CLAIM_META_DATA WHERE " +
            "IDN_CLAIM_ID=? AND IDN_TENANT_ID=?";

    public static final String DELETE_MAPPED_ATTRIBUTE_SQL = "DELETE FROM IDN_CLAIM_MAPPED_ATTRIBUTE WHERE " +
            "IDN_CLAIM_ID=? AND " +
            "IDN_TENANT_ID=?";

    public static final String GET_ALL_DIALECT_SQL = "SELECT * FROM IDN_DIALECT";

    public static final String GET_ALL_CLAIM_META_DATA_SQL = "SELECT IDN_CLAIM_ID, IDN_KEY, IDN_VALUE FROM " +
            "IDN_CLAIM_META_DATA WHERE IDN_TENANT_ID = ?";

    public static final String ADD_CLAIM_MAPPED_ATTRIBUTE_SQL = "INSERT INTO IDN_CLAIM_MAPPED_ATTRIBUTE(IDN_CLAIM_ID, " +
            "IDN_MAPPED_ATTRIBUTE_DOMAIN, IDN_MAPPED_ATTRIBUTE,IDN_TENANT_ID) VALUES (?,?,?,?)";

    public static final String ADD_CLAIM_RELATION_SQL = "INSERT INTO IDN_CLAIM_MAPPING(IDN_LOCAL_CLAIM_ID, " +
            "IDN_ADDITIONAL_CLAIM_ID," +
            "IDN_TENANT_ID) VALUES (?,?,?)";

    public static final String ADD_CLAIM_META_DATA_SQL = "INSERT INTO IDN_CLAIM_META_DATA(IDN_CLAIM_ID, " +
            "IDN_KEY,IDN_VALUE,IDN_TENANT_ID) VALUES (?,?,?,?)";

    public static final String GET_LOCAL_CLAIMS = "SELECT CLAIM_IN_DIALECT.IDN_DIALECT_URI IDN_DIALECT_URI, " +
            "CLAIM_IN_DIALECT.IDN_CLAIM_URI IDN_CLAIM_URI, CLAIM_IN_DIALECT.IDN_CLAIM_ID IDN_CLAIM_ID, " +
            "IDN_MAPPED_ATTRIBUTE, IDN_MAPPED_ATTRIBUTE_DOMAIN FROM (SELECT IDN_DIALECT_URI, IDN_CLAIM_URI, IDN_CLAIM" +
            ".IDN_ID IDN_CLAIM_ID FROM IDN_DIALECT, IDN_CLAIM WHERE IDN_DIALECT.IDN_TENANT_ID =? AND IDN_CLAIM.IDN_TENANT_ID=? AND IDN_DIALECT.IDN_ID=IDN_CLAIM.IDN_DIALECT_ID) CLAIM_IN_DIALECT INNER JOIN IDN_CLAIM_MAPPED_ATTRIBUTE ON CLAIM_IN_DIALECT.IDN_CLAIM_ID=IDN_CLAIM_MAPPED_ATTRIBUTE.IDN_CLAIM_ID";

    public static final String GET_ADDITIONAL_CLAIMS = "SELECT IDN_DIALECT.IDN_DIALECT_URI IDN_DIALECT_URI, IDN_CLAIM" +
            ".IDN_CLAIM_URI IDN_CLAIM_URI, IDN_CLAIM.IDN_ID IDN_CLAIM_ID, (SELECT IDN_CLAIM_URI FROM IDN_CLAIM WHERE " +
            "IDN_CLAIM.IDN_ID = CM.IDN_LOCAL_CLAIM_ID) IDN_MAPPED_ATTRIBUTE FROM IDN_DIALECT ,IDN_CLAIM, " +
            "IDN_CLAIM_MAPPING CM WHERE IDN_DIALECT.IDN_ID=IDN_CLAIM.IDN_DIALECT_ID AND IDN_DIALECT.IDN_TENANT_ID =? AND IDN_CLAIM.IDN_TENANT_ID=? AND IDN_CLAIM.IDN_ID = CM.IDN_ADDITIONAL_CLAIM_ID";

    public static final String GET_CLAIM_ID_SQL = "SELECT IDN_ID FROM IDN_CLAIM WHERE " +
            "IDN_CLAIM_URI=? AND IDN_TENANT_ID=?";

    public static final String GET_META_DATA_FOR_CLIAM_SQL = "SELECT * FROM IDN_CLAIM_META_DATA WHERE " +
            "IDN_CLAIM_ID=?";


    public static final String GET_CLAIMS_FOR_DIALECTT_SQL = "SELECT IDN_CLAIM_URI FROM " +
            "IDN_CLAIM, IDN_DIALECT WHERE IDN_CLAIM.IDN_DIALECT_ID=IDN_DIALECT.IDN_ID AND IDN_DIALECT_URI=? " +
            "AND IDN_CLAIM.IDN_TENANT_ID=? AND IDN_DIALECT.IDN_TENANT_ID=?";

    public static final String GET_DIALECT_ID_SQL = "SELECT IDN_ID FROM IDN_DIALECT WHERE " +
            "IDN_DIALECT_URI=? AND IDN_TENANT_ID=?";
    public static final String COUNT_DIALECTS = "SELECT COUNT(IDN_ID) FROM IDN_DIALECT WHERE " +
            "IDN_TENANT_ID=?";


    public static final String DELETE_DIALECT = "DELETE FROM IDN_DIALECT WHERE IDN_DIALECT_URI=?";

    public static final String GET_MAPPED_ATTRIBUTE = "(SELECT IDN_MAPPED_ATTRIBUTE FROM IDN_CLAIM_MAPPED_ATTRIBUTE " +
            "WHERE IDN_CLAIM_ID = (SELECT IDN_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI = ? AND IDN_TENANT_ID = ?) AND " +
            "IDN_MAPPED_ATTRIBUTE_DOMAIN is NULL) UNION (SELECT IDN_MAPPED_ATTRIBUTE FROM IDN_CLAIM_MAPPED_ATTRIBUTE " +
            " WHERE IDN_CLAIM_ID  = (SELECT IDN_LOCAL_CLAIM_ID FROM IDN_CLAIM_MAPPING WHERE IDN_ADDITIONAL_CLAIM_ID =" +
            " (SELECT IDN_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI =? AND IDN_TENANT_ID = ?)) AND " +
            "IDN_MAPPED_ATTRIBUTE_DOMAIN is NULL)";

    public static final String GET_MAPPED_ATTRIBUTE_OF_DOMAIN = "(SELECT IDN_MAPPED_ATTRIBUTE FROM " +
            "IDN_CLAIM_MAPPED_ATTRIBUTE WHERE IDN_CLAIM_ID = (SELECT IDN_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI = ? " +
            "AND IDN_TENANT_ID = ?) AND IDN_MAPPED_ATTRIBUTE_DOMAIN = ?) UNION (SELECT IDN_MAPPED_ATTRIBUTE FROM " +
            "IDN_CLAIM_MAPPED_ATTRIBUTE  WHERE IDN_CLAIM_ID  = (SELECT IDN_LOCAL_CLAIM_ID FROM IDN_CLAIM_MAPPING " +
            "WHERE IDN_ADDITIONAL_CLAIM_ID = (SELECT IDN_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI =? AND IDN_TENANT_ID  " +
            "= ?))  AND IDN_MAPPED_ATTRIBUTE_DOMAIN = ?)";

    public static final String GET_MAPPED_ATTRIBUTES = "(SELECT IDN_MAPPED_ATTRIBUTE_DOMAIN ,IDN_MAPPED_ATTRIBUTE ," +
            "IDN_DIALECT_URI FROM (SELECT IDN_ID, IDN_DIALECT_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI = ? AND " +
            "IDN_TENANT_ID = ?) CLAIM INNER JOIN IDN_CLAIM_MAPPED_ATTRIBUTE ON IDN_CLAIM_ID = CLAIM.IDN_ID INNER JOIN" +
            " IDN_DIALECT ON CLAIM.IDN_DIALECT_ID = IDN_DIALECT.IDN_ID) UNION (SELECT IDN_MAPPED_ATTRIBUTE_DOMAIN ," +
            "IDN_MAPPED_ATTRIBUTE ,IDN_DIALECT_URI FROM (SELECT IDN_LOCAL_CLAIM_ID  IDN_ID, IDN_DIALECT_ID FROM " +
            "(SELECT IDN_ID, IDN_DIALECT_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI = ? AND IDN_TENANT_ID = ?) CLAIM INNER" +
            " JOIN IDN_CLAIM_MAPPING ON IDN_ADDITIONAL_CLAIM_ID = CLAIM.IDN_ID) CLAIM INNER JOIN " +
            "IDN_CLAIM_MAPPED_ATTRIBUTE ON IDN_CLAIM_ID = CLAIM.IDN_ID INNER JOIN IDN_DIALECT ON CLAIM.IDN_DIALECT_ID" +
            " = IDN_DIALECT.IDN_ID)";

    public static final String GET_CLAIM = "SELECT IDN_KEY, IDN_VALUE  FROM IDN_CLAIM_META_DATA WHERE IDN_CLAIM_ID = " +
            "(SELECT  IDN_ID FROM IDN_CLAIM WHERE IDN_CLAIM_URI = ? AND IDN_TENANT_ID = ?)";

    public static final String GET_CLAIM_METADATA = "SELECT * FROM (SELECT IDN_ID, IDN_DIALECT_ID FROM IDN_CLAIM " +
            "WHERE IDN_CLAIM_URI = ? AND IDN_TENANT_ID = ?) CLAIM INNER JOIN IDN_CLAIM_META_DATA ON IDN_CLAIM_ID " +
            "=CLAIM.IDN_ID ";

    private ClaimDBConstants() {
    }
}
