// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine.proto

package org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto;

public interface ExecuteCallbackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.wso2.carbon.identity.graaljs.engine.proto.ExecuteCallbackResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int64 elapsed_ms = 2;</code>
   * @return The elapsedMs.
   */
  long getElapsedMs();

  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue result = 3;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue result = 3;</code>
   * @return The result.
   */
  org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getResult();
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue result = 3;</code>
   */
  org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder getResultOrBuilder();

  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; updated_bindings = 4;</code>
   */
  int getUpdatedBindingsCount();
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; updated_bindings = 4;</code>
   */
  boolean containsUpdatedBindings(
      java.lang.String key);
  /**
   * Use {@link #getUpdatedBindingsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
  getUpdatedBindings();
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; updated_bindings = 4;</code>
   */
  java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
  getUpdatedBindingsMap();
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; updated_bindings = 4;</code>
   */
  /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getUpdatedBindingsOrDefault(
      java.lang.String key,
      /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue defaultValue);
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; updated_bindings = 4;</code>
   */
  org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getUpdatedBindingsOrThrow(
      java.lang.String key);

  /**
   * <code>string error_message = 5;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 5;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
