[libdefaults]
        default_realm = WSO2.COM
        default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
        default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
        dns_lookup_kdc = true
        dns_lookup_realm = false

[realms]
        WSO2.COM = {
            kdc = 127.0.0.1
   }