DROP PROCEDURE IF EXISTS `WSO2_IDN_FLOW_CONTEXT_CLEANUP_RESTORE`;
DELIMITER $$

CREATE PROCEDURE `WSO2_IDN_FLOW_CONTEXT_CLEANUP_RESTORE`()
BEGIN
    -- ------------------------------------------
    -- DECLARE VARIABLES
    -- ------------------------------------------
    DECLARE rowCount INT;
    DECLARE enableLog BOOLEAN;

    -- ------------------------------------------
    -- CONFIGURABLE ATTRIBUTES
    -- ------------------------------------------
    SET enableLog = FALSE; -- ENABLE LOGGING [DEFAULT : FALSE]

    IF (enableLog) THEN
        SELECT 'CLEANUP DATA RESTORATION STARTED...!' AS 'INFO LOG';
    END IF;

    SELECT COUNT(1) INTO rowCount
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'IDN_FLOW_CONTEXT_STORE';

    IF (rowCount = 1) THEN
        INSERT INTO IDN_FLOW_CONTEXT_STORE (ID, TENANT_ID, FLOW_TYPE, CREATED_AT, EXPIRES_AT, FLOW_STATE_JSON)
        SELECT A.ID, A.TENANT_ID, A.FLOW_TYPE, A.CREATED_AT, A.EXPIRES_AT, A.FLOW_STATE_JSON
        FROM BAK_IDN_FLOW_CONTEXT_STORE A
        LEFT JOIN IDN_FLOW_CONTEXT_STORE B ON A.ID = B.ID
        WHERE B.ID IS NULL;

        SELECT ROW_COUNT() INTO rowCount;

        IF (enableLog) THEN
            SELECT CONCAT('CLEANUP DATA RESTORATION COMPLETED ON IDN_FLOW_CONTEXT_STORE WITH ', rowCount) AS 'INFO LOG';
        END IF;
    END IF;

    IF (enableLog) THEN
        SELECT 'CLEANUP DATA RESTORATION COMPLETED...!' AS 'INFO LOG';
    END IF;

END$$

DELIMITER ;
