// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine_grpc.proto

package org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.grpc;

public final class JsEngineGrpcProtos {
  private JsEngineGrpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024js_engine_grpc.proto\022-org.wso2.carbon." +
      "identity.graaljs.engine.proto\032\017js_engine" +
      ".proto2\256\001\n\030JsEngineStreamingService\022\221\001\n\r" +
      "ExecuteScript\022<.org.wso2.carbon.identity" +
      ".graaljs.engine.proto.StreamMessage\032<.or" +
      "g.wso2.carbon.identity.graaljs.engine.pr" +
      "oto.StreamMessage\"\000(\0010\001B\202\001\njorg.wso2.car" +
      "bon.identity.application.authentication." +
      "framework.config.model.graph.graaljs.rem" +
      "ote.proto.grpcB\022JsEngineGrpcProtosP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.getDescriptor(),
        });
    org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
