CREATE TABLE IDN_FLOW (
    ID VARCHAR(50) PRIMARY KEY,
    TENANT_ID INT,
    FLOW_NAME VARCHAR(255),
    TYPE VARCHAR(100),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    LAST_MODIFIED TIMESTAMP,
    UNIQUE (TENANT_ID, FLOW_NAME)
);

CREATE TABLE IDN_FLOW_NODE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NODE_ID VARCHAR(50),
    FLOW_ID VARCHAR(50),
    NODE_TYPE VARCHAR(100),
    IS_FIRST_NODE BOOLEAN DEFAULT FALSE,
    UNIQUE (NODE_ID, FLOW_ID),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE
);

CREATE TABLE IDN_FLOW_NODE_MAPPING (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    NEXT_NODE_ID INT,
    TRIGGERING_ELEMENT VARCHAR(100),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE,
    FOREIGN KEY (NEXT_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IDN_FLOW_PAGE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_ID VARCHAR(50),
    FLOW_NODE_ID INT,
    STEP_ID VARCHAR(50),
    PAGE_CONTENT BLOB,
    TYPE VARCHAR(100),
    FOREIGN KEY (FLOW_ID) REFERENCES IDN_FLOW(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IDN_FLOW_PAGE_META (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGE_ID INT,
    COORDINATE_X DOUBLE,
    COORDINATE_Y DOUBLE,
    HEIGHT DOUBLE,
    WIDTH DOUBLE,
    FOREIGN KEY (PAGE_ID) REFERENCES IDN_FLOW_PAGE(ID) ON DELETE CASCADE
);

CREATE TABLE IDN_FLOW_NODE_EXECUTOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FLOW_NODE_ID INT,
    EXECUTOR_NAME VARCHAR(255),
    FOREIGN KEY (FLOW_NODE_ID) REFERENCES IDN_FLOW_NODE(ID) ON DELETE CASCADE
);

CREATE TABLE IDN_FLOW_NODE_EXECUTOR_META (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EXECUTOR_ID INT,
    METADATA_NAME VARCHAR(255),
    METADATA_VALUE VARCHAR(255),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES IDN_FLOW_NODE_EXECUTOR(ID) ON DELETE CASCADE
);
