/*
 * Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.action.execution.api.model;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * This class models the UserStore.
 * UserStore is the entity that represents the user store of the user for whom the action is triggered for.
 * User store is present when the user's profile is managed within the system only.
 */
public class UserStore {

    private String id;
    private String name;

    public UserStore(String name) {

        setName(name);
    }

    public String getId() {

        return id;
    }

    public String getName() {

        return name;
    }

    public void setName(String name) {

        /*
         * As of now user store id is generated by encoding the user store name.
         */
        this.id = name != null ? Base64.getEncoder().encodeToString(name.getBytes(StandardCharsets.UTF_8)) : null;
        this.name = name;
    }
}
