CREATE OR REPLACE PROCEDURE WSO2_CONFIRMATION_CODE_CLEANUP_RESTORE
BEGIN

-- ------------------------------------------
-- DECLARE VARIABLES
-- ------------------------------------------
DECLARE rowCount INT;
DECLARE enableLog SMALLINT;
DECLARE sqlStmt VARCHAR(5000);

-- ------------------------------------------
-- CONFIGURABLE ATTRIBUTES
-- ------------------------------------------
SET enableLog = 1; -- ENABLE LOGGING [DEFAULT : TRUE]

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('CLEANUP DATA RESTORATION STARTED .... !');
END IF;

SELECT COUNT(*) INTO rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'IDN_RECOVERY_FLOW_DATA';
IF (rowCount = 1) THEN

SELECT COUNT(*) INTO rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'BAK_IDN_RECOVERY_FLOW_DATA';

IF (rowCount = 1) THEN
        SET sqlStmt = 'INSERT INTO IDN_RECOVERY_FLOW_DATA SELECT A.* FROM BAK_IDN_RECOVERY_FLOW_DATA A LEFT JOIN IDN_RECOVERY_FLOW_DATA B ON A.RECOVERY_FLOW_ID = B.RECOVERY_FLOW_ID WHERE B.RECOVERY_FLOW_ID IS NULL';
EXECUTE IMMEDIATE sqlStmt;

GET DIAGNOSTICS rowCount = ROW_COUNT;
IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('CLEANUP DATA RESTORATION COMPLETED ON IDN_RECOVERY_FLOW_DATA WITH ' || rowCount);
END IF;
END IF;

END IF;

SELECT COUNT(*) INTO rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'IDN_RECOVERY_DATA';
IF (rowCount = 1) THEN

SELECT COUNT(*) INTO rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'BAK_IDN_RECOVERY_DATA';

IF (rowCount = 1) THEN
        SET sqlStmt = 'INSERT INTO IDN_RECOVERY_DATA SELECT A.* FROM BAK_IDN_RECOVERY_DATA A LEFT JOIN IDN_RECOVERY_DATA B ON A.CODE = B.CODE WHERE B.CODE IS NULL';
EXECUTE IMMEDIATE sqlStmt;

GET DIAGNOSTICS rowCount = ROW_COUNT;
IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('CLEANUP DATA RESTORATION COMPLETED ON IDN_RECOVERY_DATA WITH ' || rowCount);
END IF;
END IF;

END IF;

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('CLEANUP DATA RESTORATION COMPLETED .... !');
END IF;

END/
