CREATE OR REPLACE PROCEDURE WSO2_CONFIRMATION_CODE_CLEANUP

BEGIN

-- ------------------------------------------
-- DECLARE VARIABLES
-- ------------------------------------------
DECLARE batchSize INT;
DECLARE chunkSize INT;
DECLARE batchCount INT;
DECLARE chunkCount INT;
DECLARE rowCount INT;
DECLARE v_rowCount INT;
DECLARE enableLog SMALLINT;
DECLARE backupTables SMALLINT;
DECLARE cleanUpCodesTimeLimit INT;
DECLARE cleanUpDateTimeLimit TIMESTAMP;
DECLARE cleanUpDateTimeLimitStr VARCHAR(26);

-- ------------------------------------------
-- CONFIGURABLE VARIABLES
-- ------------------------------------------
SET batchSize    = 10000; -- SET BATCH SIZE FOR AVOID TABLE LOCKS [DEFAULT : 10000]
SET chunkSize    = 500000; -- CHUNK WISE DELETE FOR LARGE TABLES [DEFAULT : 500000]
SET enableLog    = 0; -- ENABLE LOGGING [DEFAULT : 0]
SET backupTables = 0; -- SET IF RECOVERY DATA TABLE NEEDS TO BE BACKED-UP BEFORE DELETE [DEFAULT : 0]. WILL DROP THE PREVIOUS BACKUP TABLES IN NEXT ITERATION
SET cleanUpCodesTimeLimit = 720;  -- SET SAFE PERIOD OF HOURS FOR CODE DELETE [DEFAULT : 720 hrs (30 days)]. CODES OLDER THAN THE NUMBER OF HOURS DEFINED HERE WILL BE DELETED.

SET rowCount = 0;
SET batchCount = 1;
SET chunkCount = 1;
SET cleanUpDateTimeLimit = CURRENT TIMESTAMP - cleanUpCodesTimeLimit HOUR;
SET cleanUpDateTimeLimitStr = CHAR(cleanUpDateTimeLimit);

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('WSO2_CONFIRMATION_CODE_CLEANUP() STARTED...!');
END IF;

-- ------------------------------------------
-- BACKUP DATA
-- ------------------------------------------

IF (backupTables = 1) THEN
    IF (enableLog = 1) THEN
        CALL DBMS_OUTPUT.PUT_LINE('TABLE BACKUP STARTED...!');
    END IF;

    IF (EXISTS (SELECT NAME FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'BAK_IDN_RECOVERY_DATA')) THEN
        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('DELETING OLD IDN_RECOVERY_DATA BACKUP...');
        END IF;
        DROP TABLE BAK_IDN_RECOVERY_DATA;
    END IF;
    CREATE TABLE BAK_IDN_RECOVERY_DATA AS (SELECT * FROM IDN_RECOVERY_DATA) WITH DATA;

    SELECT COUNT(*) INTO v_rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'IDN_RECOVERY_FLOW_DATA';
    IF (v_rowCount > 0) THEN
        IF (EXISTS (SELECT NAME FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'BAK_IDN_RECOVERY_FLOW_DATA')) THEN
            IF (enableLog = 1) THEN
                CALL DBMS_OUTPUT.PUT_LINE('DELETING OLD IDN_RECOVERY_FLOW_DATA BACKUP...');
            END IF;
            EXECUTE IMMEDIATE 'DROP TABLE BAK_IDN_RECOVERY_FLOW_DATA';
        END IF;
        EXECUTE IMMEDIATE 'CREATE TABLE BAK_IDN_RECOVERY_FLOW_DATA AS (SELECT * FROM IDN_RECOVERY_FLOW_DATA) WITH DATA';
    END IF;
    COMMIT;
END IF;

-- ------------------------------------------
-- CLEANUP IDN_RECOVERY_DATA
-- ------------------------------------------

WHILE (chunkCount > 0)
DO
    -- CREATE CHUNK TABLE
    DROP TABLE IF EXISTS IDN_RECOVERY_DATA_CHUNK_TMP;
    CREATE TABLE IDN_RECOVERY_DATA_CHUNK_TMP AS (SELECT CODE FROM IDN_RECOVERY_DATA) WITH NO DATA;
    INSERT INTO IDN_RECOVERY_DATA_CHUNK_TMP SELECT CODE FROM IDN_RECOVERY_DATA WHERE cleanUpDateTimeLimit > TIME_CREATED LIMIT chunkSize;
    GET DIAGNOSTICS v_rowCount = ROW_COUNT;
    SET chunkCount = v_rowCount;
    CREATE INDEX IDN_RECOVERY_DATA_CHUNK_TMP_INDX ON IDN_RECOVERY_DATA_CHUNK_TMP (CODE);
    COMMIT;

    IF (enableLog = 1) THEN
        CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_RECOVERY_DATA_CHUNK_TMP...');
    END IF;

    -- BATCH LOOP
    SET batchCount = 1;
    WHILE (batchCount > 0)
    DO
        -- CREATE BATCH TABLE
        DROP TABLE IF EXISTS IDN_RECOVERY_DATA_BATCH_TMP;
        CREATE TABLE IDN_RECOVERY_DATA_BATCH_TMP AS (SELECT CODE FROM IDN_RECOVERY_DATA_CHUNK_TMP) WITH NO DATA;
        INSERT INTO IDN_RECOVERY_DATA_BATCH_TMP SELECT CODE FROM IDN_RECOVERY_DATA_CHUNK_TMP LIMIT batchSize;
        GET DIAGNOSTICS v_rowCount = ROW_COUNT;
        SET batchCount = v_rowCount;
        CREATE INDEX IDN_RECOVERY_DATA_BATCH_TMP_INDX ON IDN_RECOVERY_DATA_BATCH_TMP (CODE);
        COMMIT;

        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_RECOVERY_DATA_BATCH_TMP...');
        END IF;

        -- BATCH DELETION
        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('BATCH DELETE STARTED ON IDN_RECOVERY_DATA...');
        END IF;
        DELETE FROM IDN_RECOVERY_DATA WHERE CODE IN (SELECT CODE FROM IDN_RECOVERY_DATA_BATCH_TMP);
        GET DIAGNOSTICS rowCount = ROW_COUNT;
        COMMIT;

        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('BATCH DELETE FINISHED ON IDN_RECOVERY_DATA : ' || rowCount);
        END IF;

        -- DELETE FROM CHUNK
        DELETE FROM IDN_RECOVERY_DATA_CHUNK_TMP WHERE CODE IN (SELECT CODE FROM IDN_RECOVERY_DATA_BATCH_TMP);
    END WHILE;
END WHILE;

-- ------------------------------------------
-- CLEANUP IDN_RECOVERY_FLOW_DATA
-- ------------------------------------------
-- NOTE: IDN_RECOVERY_FLOW_DATA only exists on schemas with the recovery V2 API.
-- This block is intentionally built with dynamic SQL (EXECUTE IMMEDIATE) and
-- guarded by the catalog existence check below so the procedure still compiles
-- and runs on older schemas where the table is absent. Do not convert it to
-- static SQL.

SELECT COUNT(*) INTO v_rowCount FROM SYSIBM.SYSTABLES WHERE CREATOR = CURRENT SCHEMA AND NAME = 'IDN_RECOVERY_FLOW_DATA';
IF (v_rowCount > 0) THEN
    SET chunkCount = 1;
    WHILE (chunkCount > 0)
    DO
        -- CREATE CHUNK TABLE
        EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS IDN_RECOVERY_FLOW_DATA_CHUNK_TMP';
        EXECUTE IMMEDIATE 'CREATE TABLE IDN_RECOVERY_FLOW_DATA_CHUNK_TMP AS (SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA) WITH NO DATA';
        EXECUTE IMMEDIATE 'INSERT INTO IDN_RECOVERY_FLOW_DATA_CHUNK_TMP SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA WHERE TIMESTAMP(''' || cleanUpDateTimeLimitStr || ''') > TIME_CREATED FETCH FIRST ' || CAST(chunkSize AS VARCHAR(10)) || ' ROWS ONLY';
        GET DIAGNOSTICS v_rowCount = ROW_COUNT;
        SET chunkCount = v_rowCount;
        EXECUTE IMMEDIATE 'CREATE INDEX IDN_RECOVERY_FLOW_DATA_CHUNK_TMP_INDX ON IDN_RECOVERY_FLOW_DATA_CHUNK_TMP (RECOVERY_FLOW_ID)';
        COMMIT;

        IF (enableLog = 1) THEN
            CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_RECOVERY_FLOW_DATA_CHUNK_TMP...');
        END IF;

        -- BATCH LOOP
        SET batchCount = 1;
        WHILE (batchCount > 0)
        DO
            -- CREATE BATCH TABLE
            EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS IDN_RECOVERY_FLOW_DATA_BATCH_TMP';
            EXECUTE IMMEDIATE 'CREATE TABLE IDN_RECOVERY_FLOW_DATA_BATCH_TMP AS (SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA_CHUNK_TMP) WITH NO DATA';
            EXECUTE IMMEDIATE 'INSERT INTO IDN_RECOVERY_FLOW_DATA_BATCH_TMP SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA_CHUNK_TMP FETCH FIRST ' || CAST(batchSize AS VARCHAR(10)) || ' ROWS ONLY';
            GET DIAGNOSTICS v_rowCount = ROW_COUNT;
            SET batchCount = v_rowCount;
            EXECUTE IMMEDIATE 'CREATE INDEX IDN_RECOVERY_FLOW_DATA_BATCH_TMP_INDX ON IDN_RECOVERY_FLOW_DATA_BATCH_TMP (RECOVERY_FLOW_ID)';
            COMMIT;

            IF (enableLog = 1) THEN
                CALL DBMS_OUTPUT.PUT_LINE('CREATED IDN_RECOVERY_FLOW_DATA_BATCH_TMP...');
            END IF;

            -- BATCH DELETION
            IF (enableLog = 1) THEN
                CALL DBMS_OUTPUT.PUT_LINE('BATCH DELETE STARTED ON IDN_RECOVERY_FLOW_DATA...');
            END IF;
            EXECUTE IMMEDIATE 'DELETE FROM IDN_RECOVERY_FLOW_DATA WHERE RECOVERY_FLOW_ID IN (SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA_BATCH_TMP)';
            GET DIAGNOSTICS rowCount = ROW_COUNT;
            COMMIT;

            IF (enableLog = 1) THEN
                CALL DBMS_OUTPUT.PUT_LINE('BATCH DELETE FINISHED ON IDN_RECOVERY_FLOW_DATA : ' || rowCount);
            END IF;

            -- DELETE FROM CHUNK
            EXECUTE IMMEDIATE 'DELETE FROM IDN_RECOVERY_FLOW_DATA_CHUNK_TMP WHERE RECOVERY_FLOW_ID IN (SELECT RECOVERY_FLOW_ID FROM IDN_RECOVERY_FLOW_DATA_BATCH_TMP)';
        END WHILE;
    END WHILE;
END IF;

-- DELETE TEMP TABLES
DROP TABLE IF EXISTS IDN_RECOVERY_DATA_BATCH_TMP;
DROP TABLE IF EXISTS IDN_RECOVERY_DATA_CHUNK_TMP;
DROP TABLE IF EXISTS IDN_RECOVERY_FLOW_DATA_BATCH_TMP;
DROP TABLE IF EXISTS IDN_RECOVERY_FLOW_DATA_CHUNK_TMP;
COMMIT;

IF (enableLog = 1) THEN
    CALL DBMS_OUTPUT.PUT_LINE('CLEANUP COMPLETED...!');
END IF;

END/
