CREATE TABLE IF NOT EXISTS IDN_DEVICE (
    ID              CHAR(36)      NOT NULL,
    DEVICE_NAME     VARCHAR(255)  NOT NULL,
    DEVICE_MODEL    VARCHAR(255),
    PUBLIC_KEY      VARCHAR(4096) NOT NULL,
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    REGISTERED_AT   TIMESTAMP     NOT NULL,
    METADATA        VARCHAR(4096) NULL,
    TENANT_ID       INTEGER       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS IDN_USER_DEVICE (
    DEVICE_ID       CHAR(36)      NOT NULL,
    USER_ID         VARCHAR(255)  NOT NULL,
    TENANT_ID       INTEGER       NOT NULL,
    PRIMARY KEY (DEVICE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES IDN_DEVICE (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_IUD_USER_TENANT ON IDN_USER_DEVICE (USER_ID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDV_STATUS ON IDN_DEVICE (STATUS, TENANT_ID);
