package org.wso2.carbon.identity.framework.async.status.mgt.constant;

public class SQLConstants {
    public static final String CREATE_B2B_RESOURCE_SHARING_OPERATION = "INSERT INTO UM_SHARING_OPERATION(" +
            "UM_SHARING_OPERATION_ID, UM_SHARING_OPERATION_TYPE, UM_RESIDENT_RESOURCE_ID, UM_RESOURCE_TYPE," +
            "UM_SHARING_POLICY, UM_RESIDENT_ORG_ID, UM_OPERATION_INITIATOR_ID, UM_SHARING_OPERATION_STATUS," +
            "UM_CREATED_TIME, UM_LAST_MODIFIED";

 }
