CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(36) NOT NULL,
    ENDPOINT VARCHAR(2048) NOT NULL,
    NAME VARCHAR(1024),
    SECRET VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(32) NOT NULL,
    EVENT_SCHEMA_NAME VARCHAR(64) NOT NULL,
    EVENT_SCHEMA_URI VARCHAR(255) NOT NULL,
    EVENT_SCHEMA_VERSION VARCHAR(32) NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(TENANT_ID, ENDPOINT)
    );

-- Table: IDN_WEBHOOK_EVENTS
CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_EVENTS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    WEBHOOK_ID INTEGER NOT NULL,
    EVENT_NAME VARCHAR(255) NOT NULL,
    UNIQUE (WEBHOOK_ID, EVENT_NAME),
    PRIMARY KEY (ID),
    UNIQUE(WEBHOOK_ID, EVENT_NAME),
    CONSTRAINT FK_IDN_WEBHOOK_EVENTS_WEBHOOKS
    FOREIGN KEY (WEBHOOK_ID)
    REFERENCES IDN_WEBHOOK(ID)
    ON DELETE CASCADE
    );

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_TENANT ON IDN_WEBHOOK(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_UUID ON IDN_WEBHOOK(UUID);
