CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(32) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(64) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(TENANT_ID, ENDPOINT)
    );

-- Table: IDN_WEBHOOK_CHANNELS
CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNELS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    UNIQUE (WEBHOOK_ID, CHANNEL_URI),
    PRIMARY KEY (ID),
    UNIQUE(WEBHOOK_ID, CHANNEL_URI),
    CONSTRAINT FK_IDN_WEBHOOK_CHANNELS_WEBHOOKS
    FOREIGN KEY (WEBHOOK_ID)
    REFERENCES IDN_WEBHOOK(ID)
    ON DELETE CASCADE
    );

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_TENANT ON IDN_WEBHOOK(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_UUID ON IDN_WEBHOOK(UUID);
