CREATE TABLE IF NOT EXISTS IDN_WEBHOOK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(36) NOT NULL,
    ENDPOINT VARCHAR(1024) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    SECRET_ALIAS VARCHAR(1024) NOT NULL,
    VERSION VARCHAR(32) NOT NULL,
    EVENT_PROFILE_NAME VARCHAR(64) NOT NULL,
    EVENT_PROFILE_URI VARCHAR(255) NOT NULL,
    EVENT_PROFILE_VERSION VARCHAR(32) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(TENANT_ID, ENDPOINT)
    );

-- Table: IDN_WEBHOOK_CHANNELS
CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNELS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    -- Matches the DDL of a fresh deployment. Tests of the insert used before the channel UUID migration drop
    -- the NOT NULL constraint for their duration.
    UUID VARCHAR(36) NOT NULL,
    WEBHOOK_ID INTEGER NOT NULL,
    CHANNEL_URI VARCHAR(255) NOT NULL,
    CHANNEL_SUBSCRIPTION_STATUS VARCHAR(30),
    PRIMARY KEY (ID),
    UNIQUE(UUID),
    UNIQUE(WEBHOOK_ID, CHANNEL_URI),
    CONSTRAINT FK_IDN_WEBHOOK_CHANNELS_WEBHOOKS
    FOREIGN KEY (WEBHOOK_ID)
    REFERENCES IDN_WEBHOOK(ID)
    ON DELETE CASCADE
    );

-- Table: IDN_WEBHOOK_CHANNEL_ORG_SUB
-- Which descendant organizations feed a given webhook channel.
-- TOPIC_UUID and TOPIC are populated only under the PublisherSubscriber adapter; under the
-- Publisher (HTTP) adapter no topics exist and both stay NULL.
-- SUBSCRIBED_ORG_TENANT_ID drives publish-time resolution; SUBSCRIBED_ORG_ID serves the REST
-- layer, which works in organization ids. The mapping between them is fixed at organization
-- creation, so holding both is safe.
CREATE TABLE IF NOT EXISTS IDN_WEBHOOK_CHANNEL_ORG_SUB (
    CHANNEL_UUID VARCHAR(36) NOT NULL,
    SUBSCRIBED_ORG_TENANT_ID INTEGER NOT NULL,
    SUBSCRIBED_ORG_ID VARCHAR(36) NOT NULL,
    TOPIC_UUID VARCHAR(36),
    TOPIC VARCHAR(255),
    PRIMARY KEY (CHANNEL_UUID, SUBSCRIBED_ORG_TENANT_ID),
    CONSTRAINT FK_IDN_WEBHOOK_CHANNEL_ORG_SUB_CHANNELS
    FOREIGN KEY (CHANNEL_UUID)
    REFERENCES IDN_WEBHOOK_CHANNELS(UUID)
    ON DELETE CASCADE
    );

-- The publish-time lookup. The primary key cannot serve it: SUBSCRIBED_ORG_TENANT_ID is the
-- trailing key column, while publish-time resolution filters on it alone.
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_CHANNEL_ORG_SUB_ORG
    ON IDN_WEBHOOK_CHANNEL_ORG_SUB(SUBSCRIBED_ORG_TENANT_ID);

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_TENANT ON IDN_WEBHOOK(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IDN_WEBHOOK_UUID ON IDN_WEBHOOK(UUID);
