// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine.proto

package org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto;

/**
 * Protobuf type {@code org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse}
 */
public final class ContextPropertyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse)
    ContextPropertyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContextPropertyResponse.newBuilder() to construct.
  private ContextPropertyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContextPropertyResponse() {
    errorMessage_ = "";
    proxyType_ = "";
    memberKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContextPropertyResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_ContextPropertyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_ContextPropertyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.class, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue value_;
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getValue() {
    return value_ == null ? org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance() : value_;
  }
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   */
  @java.lang.Override
  public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder getValueOrBuilder() {
    return value_ == null ? org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance() : value_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_PROXY_FIELD_NUMBER = 4;
  private boolean isProxy_ = false;
  /**
   * <pre>
   * If true, value represents a proxy needing further access
   * </pre>
   *
   * <code>bool is_proxy = 4;</code>
   * @return The isProxy.
   */
  @java.lang.Override
  public boolean getIsProxy() {
    return isProxy_;
  }

  public static final int PROXY_TYPE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object proxyType_ = "";
  /**
   * <pre>
   * Type for creating nested proxy
   * </pre>
   *
   * <code>string proxy_type = 5;</code>
   * @return The proxyType.
   */
  @java.lang.Override
  public java.lang.String getProxyType() {
    java.lang.Object ref = proxyType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proxyType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Type for creating nested proxy
   * </pre>
   *
   * <code>string proxy_type = 5;</code>
   * @return The bytes for proxyType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProxyTypeBytes() {
    java.lang.Object ref = proxyType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proxyType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBER_KEYS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList memberKeys_;
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @return A list containing the memberKeys.
   */
  public com.google.protobuf.ProtocolStringList
      getMemberKeysList() {
    return memberKeys_;
  }
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @return The count of memberKeys.
   */
  public int getMemberKeysCount() {
    return memberKeys_.size();
  }
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @param index The index of the element to return.
   * @return The memberKeys at the given index.
   */
  public java.lang.String getMemberKeys(int index) {
    return memberKeys_.get(index);
  }
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the memberKeys at the given index.
   */
  public com.google.protobuf.ByteString
      getMemberKeysBytes(int index) {
    return memberKeys_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
    }
    if (isProxy_ != false) {
      output.writeBool(4, isProxy_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(proxyType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, proxyType_);
    }
    for (int i = 0; i < memberKeys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, memberKeys_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
    }
    if (isProxy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isProxy_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(proxyType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, proxyType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < memberKeys_.size(); i++) {
        dataSize += computeStringSizeNoTag(memberKeys_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMemberKeysList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse)) {
      return super.equals(obj);
    }
    org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse other = (org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (getIsProxy()
        != other.getIsProxy()) return false;
    if (!getProxyType()
        .equals(other.getProxyType())) return false;
    if (!getMemberKeysList()
        .equals(other.getMemberKeysList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + IS_PROXY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsProxy());
    hash = (37 * hash) + PROXY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProxyType().hashCode();
    if (getMemberKeysCount() > 0) {
      hash = (37 * hash) + MEMBER_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberKeysList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse)
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_ContextPropertyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_ContextPropertyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.class, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.Builder.class);
    }

    // Construct using org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      errorMessage_ = "";
      isProxy_ = false;
      proxyType_ = "";
      memberKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_ContextPropertyResponse_descriptor;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse getDefaultInstanceForType() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse build() {
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse buildPartial() {
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse result = new org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse result) {
      if (((bitField0_ & 0x00000020) != 0)) {
        memberKeys_ = memberKeys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.memberKeys_ = memberKeys_;
    }

    private void buildPartial0(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isProxy_ = isProxy_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.proxyType_ = proxyType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse) {
        return mergeFrom((org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse other) {
      if (other == org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getIsProxy() != false) {
        setIsProxy(other.getIsProxy());
      }
      if (!other.getProxyType().isEmpty()) {
        proxyType_ = other.proxyType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.memberKeys_.isEmpty()) {
        if (memberKeys_.isEmpty()) {
          memberKeys_ = other.memberKeys_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureMemberKeysIsMutable();
          memberKeys_.addAll(other.memberKeys_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              isProxy_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              proxyType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureMemberKeysIsMutable();
              memberKeys_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.Builder, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder> valueBuilder_;
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     * @return The value.
     */
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public Builder setValue(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public Builder setValue(
        org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public Builder mergeValue(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          value_ != null &&
          value_ != org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.Builder getValueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.Builder, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.Builder, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean isProxy_ ;
    /**
     * <pre>
     * If true, value represents a proxy needing further access
     * </pre>
     *
     * <code>bool is_proxy = 4;</code>
     * @return The isProxy.
     */
    @java.lang.Override
    public boolean getIsProxy() {
      return isProxy_;
    }
    /**
     * <pre>
     * If true, value represents a proxy needing further access
     * </pre>
     *
     * <code>bool is_proxy = 4;</code>
     * @param value The isProxy to set.
     * @return This builder for chaining.
     */
    public Builder setIsProxy(boolean value) {
      
      isProxy_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, value represents a proxy needing further access
     * </pre>
     *
     * <code>bool is_proxy = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsProxy() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isProxy_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object proxyType_ = "";
    /**
     * <pre>
     * Type for creating nested proxy
     * </pre>
     *
     * <code>string proxy_type = 5;</code>
     * @return The proxyType.
     */
    public java.lang.String getProxyType() {
      java.lang.Object ref = proxyType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proxyType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Type for creating nested proxy
     * </pre>
     *
     * <code>string proxy_type = 5;</code>
     * @return The bytes for proxyType.
     */
    public com.google.protobuf.ByteString
        getProxyTypeBytes() {
      java.lang.Object ref = proxyType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proxyType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Type for creating nested proxy
     * </pre>
     *
     * <code>string proxy_type = 5;</code>
     * @param value The proxyType to set.
     * @return This builder for chaining.
     */
    public Builder setProxyType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      proxyType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type for creating nested proxy
     * </pre>
     *
     * <code>string proxy_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProxyType() {
      proxyType_ = getDefaultInstance().getProxyType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type for creating nested proxy
     * </pre>
     *
     * <code>string proxy_type = 5;</code>
     * @param value The bytes for proxyType to set.
     * @return This builder for chaining.
     */
    public Builder setProxyTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      proxyType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList memberKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMemberKeysIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        memberKeys_ = new com.google.protobuf.LazyStringArrayList(memberKeys_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @return A list containing the memberKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getMemberKeysList() {
      return memberKeys_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @return The count of memberKeys.
     */
    public int getMemberKeysCount() {
      return memberKeys_.size();
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param index The index of the element to return.
     * @return The memberKeys at the given index.
     */
    public java.lang.String getMemberKeys(int index) {
      return memberKeys_.get(index);
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the memberKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getMemberKeysBytes(int index) {
      return memberKeys_.getByteString(index);
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param index The index to set the value at.
     * @param value The memberKeys to set.
     * @return This builder for chaining.
     */
    public Builder setMemberKeys(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMemberKeysIsMutable();
      memberKeys_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param value The memberKeys to add.
     * @return This builder for chaining.
     */
    public Builder addMemberKeys(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMemberKeysIsMutable();
      memberKeys_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param values The memberKeys to add.
     * @return This builder for chaining.
     */
    public Builder addAllMemberKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureMemberKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, memberKeys_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberKeys() {
      memberKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Available member keys for this object
     * </pre>
     *
     * <code>repeated string member_keys = 6;</code>
     * @param value The bytes of the memberKeys to add.
     * @return This builder for chaining.
     */
    public Builder addMemberKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMemberKeysIsMutable();
      memberKeys_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse)
  }

  // @@protoc_insertion_point(class_scope:org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse)
  private static final org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse();
  }

  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContextPropertyResponse>
      PARSER = new com.google.protobuf.AbstractParser<ContextPropertyResponse>() {
    @java.lang.Override
    public ContextPropertyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContextPropertyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContextPropertyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.ContextPropertyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

