// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine.proto

package org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto;

public interface ContextPropertyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.wso2.carbon.identity.graaljs.engine.proto.ContextPropertyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   * @return The value.
   */
  org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getValue();
  /**
   * <code>.org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue value = 2;</code>
   */
  org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValueOrBuilder getValueOrBuilder();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * If true, value represents a proxy needing further access
   * </pre>
   *
   * <code>bool is_proxy = 4;</code>
   * @return The isProxy.
   */
  boolean getIsProxy();

  /**
   * <pre>
   * Type for creating nested proxy
   * </pre>
   *
   * <code>string proxy_type = 5;</code>
   * @return The proxyType.
   */
  java.lang.String getProxyType();
  /**
   * <pre>
   * Type for creating nested proxy
   * </pre>
   *
   * <code>string proxy_type = 5;</code>
   * @return The bytes for proxyType.
   */
  com.google.protobuf.ByteString
      getProxyTypeBytes();

  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @return A list containing the memberKeys.
   */
  java.util.List<java.lang.String>
      getMemberKeysList();
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @return The count of memberKeys.
   */
  int getMemberKeysCount();
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @param index The index of the element to return.
   * @return The memberKeys at the given index.
   */
  java.lang.String getMemberKeys(int index);
  /**
   * <pre>
   * Available member keys for this object
   * </pre>
   *
   * <code>repeated string member_keys = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the memberKeys at the given index.
   */
  com.google.protobuf.ByteString
      getMemberKeysBytes(int index);
}
