// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine.proto

package org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto;

/**
 * Protobuf type {@code org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap}
 */
public final class SerializedMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap)
    SerializedMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SerializedMap.newBuilder() to construct.
  private SerializedMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SerializedMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SerializedMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetEntries();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.class, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.Builder.class);
  }

  public static final int ENTRIES_FIELD_NUMBER = 1;
  private static final class EntriesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>newDefaultInstance(
                org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_EntriesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> entries_;
  private com.google.protobuf.MapField<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
  internalGetEntries() {
    if (entries_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EntriesDefaultEntryHolder.defaultEntry);
    }
    return entries_;
  }
  public int getEntriesCount() {
    return internalGetEntries().getMap().size();
  }
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
   */
  @java.lang.Override
  public boolean containsEntries(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetEntries().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEntriesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> getEntries() {
    return getEntriesMap();
  }
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> getEntriesMap() {
    return internalGetEntries().getMap();
  }
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getEntriesOrDefault(
      java.lang.String key,
      /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> map =
        internalGetEntries().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
   */
  @java.lang.Override
  public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getEntriesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> map =
        internalGetEntries().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEntries(),
        EntriesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> entry
         : internalGetEntries().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
      entries__ = EntriesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap)) {
      return super.equals(obj);
    }
    org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap other = (org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap) obj;

    if (!internalGetEntries().equals(
        other.internalGetEntries())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetEntries().getMap().isEmpty()) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEntries().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap)
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetEntries();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableEntries();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.class, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.Builder.class);
    }

    // Construct using org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableEntries().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.JsEngineProtos.internal_static_org_wso2_carbon_identity_graaljs_engine_proto_SerializedMap_descriptor;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap getDefaultInstanceForType() {
      return org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap build() {
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap buildPartial() {
      org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap result = new org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entries_ = internalGetEntries();
        result.entries_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap) {
        return mergeFrom((org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap other) {
      if (other == org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap.getDefaultInstance()) return this;
      internalGetMutableEntries().mergeFrom(
          other.internalGetEntries());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
              entries__ = input.readMessage(
                  EntriesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableEntries().getMutableMap().put(
                  entries__.getKey(), entries__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> entries_;
    private com.google.protobuf.MapField<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
        internalGetEntries() {
      if (entries_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntriesDefaultEntryHolder.defaultEntry);
      }
      return entries_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
        internalGetMutableEntries() {
      if (entries_ == null) {
        entries_ = com.google.protobuf.MapField.newMapField(
            EntriesDefaultEntryHolder.defaultEntry);
      }
      if (!entries_.isMutable()) {
        entries_ = entries_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return entries_;
    }
    public int getEntriesCount() {
      return internalGetEntries().getMap().size();
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    @java.lang.Override
    public boolean containsEntries(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEntries().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntriesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> getEntries() {
      return getEntriesMap();
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> getEntriesMap() {
      return internalGetEntries().getMap();
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getEntriesOrDefault(
        java.lang.String key,
        /* nullable */
org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> map =
          internalGetEntries().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    @java.lang.Override
    public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue getEntriesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> map =
          internalGetEntries().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearEntries() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableEntries().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    public Builder removeEntries(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableEntries().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue>
        getMutableEntries() {
      bitField0_ |= 0x00000001;
      return internalGetMutableEntries().getMutableMap();
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    public Builder putEntries(
        java.lang.String key,
        org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableEntries().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .org.wso2.carbon.identity.graaljs.engine.proto.SerializedValue&gt; entries = 1;</code>
     */
    public Builder putAllEntries(
        java.util.Map<java.lang.String, org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedValue> values) {
      internalGetMutableEntries().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap)
  }

  // @@protoc_insertion_point(class_scope:org.wso2.carbon.identity.graaljs.engine.proto.SerializedMap)
  private static final org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap();
  }

  public static org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SerializedMap>
      PARSER = new com.google.protobuf.AbstractParser<SerializedMap>() {
    @java.lang.Override
    public SerializedMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SerializedMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SerializedMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.carbon.identity.application.authentication.framework.config.model.graph.graaljs.remote.proto.SerializedMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

