CREATE TABLE IDN_AUTH_SESSION_STORE (
            SESSION_ID VARCHAR (100) NOT NULL,
            SESSION_TYPE VARCHAR(100) NOT NULL,
            OPERATION VARCHAR(10) NOT NULL,
            SESSION_OBJECT BLOB,
            TIME_CREATED BIGINT,
            TENANT_ID INTEGER DEFAULT -1,
            EXPIRY_TIME BIGINT,
            PRIMARY KEY (SESSION_ID, SESSION_TYPE, TIME_CREATED, OPERATION)
);

CREATE TABLE IF NOT EXISTS IDN_AUTH_USER (
    USER_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DOMAIN_NAME VARCHAR(255) NOT NULL,
    IDP_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT USER_STORE_CONSTRAINT UNIQUE (USER_NAME, TENANT_ID, DOMAIN_NAME, IDP_ID)
);

CREATE TABLE IF NOT EXISTS IDN_AUTH_USER_SESSION_MAPPING (
    USER_ID VARCHAR(255) NOT NULL,
    SESSION_ID VARCHAR(255) NOT NULL,
    CONSTRAINT USER_SESSION_STORE_CONSTRAINT UNIQUE (USER_ID, SESSION_ID)
);

CREATE INDEX IDX_USER_ID ON IDN_AUTH_USER_SESSION_MAPPING (USER_ID);
CREATE INDEX IDX_SESSION_ID ON IDN_AUTH_USER_SESSION_MAPPING (SESSION_ID);

CREATE TABLE IF NOT EXISTS IDN_AUTH_SESSION_META_DATA (
    SESSION_ID VARCHAR (100) NOT NULL,
    PROPERTY_TYPE VARCHAR (100) NOT NULL,
    `VALUE` VARCHAR (255) NOT NULL,
    PRIMARY KEY (SESSION_ID, PROPERTY_TYPE, `VALUE`)
);

CREATE TABLE IF NOT EXISTS IDN_AUTH_SESSION_APP_INFO (
    SESSION_ID VARCHAR (100) NOT NULL,
    SUBJECT VARCHAR (100) NOT NULL,
    APP_ID INTEGER NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR (255) NOT NULL,
    PRIMARY KEY (SESSION_ID, SUBJECT, APP_ID, INBOUND_AUTH_TYPE)
);

CREATE INDEX IDX_AUTH_SAI_UN_AID_SID ON IDN_AUTH_SESSION_APP_INFO (SUBJECT, APP_ID, SESSION_ID);
CREATE INDEX IDX_AUTH_SAI_AID ON IDN_AUTH_SESSION_APP_INFO (APP_ID);

CREATE TABLE IF NOT EXISTS IDP (
  ID                         INTEGER               AUTO_INCREMENT,
  TENANT_ID                  INTEGER,
  NAME                       VARCHAR(254) NOT NULL,
  IS_ENABLED                 CHAR(1)      NOT NULL DEFAULT '1',
  IS_PRIMARY                 CHAR(1)      NOT NULL DEFAULT '0',
  HOME_REALM_ID              VARCHAR(254),
  IMAGE                      MEDIUMBLOB,
  CERTIFICATE                BLOB,
  ALIAS                      VARCHAR(254),
  INBOUND_PROV_ENABLED       CHAR(1)      NOT NULL DEFAULT '0',
  INBOUND_PROV_USER_STORE_ID VARCHAR(254),
  USER_CLAIM_URI             VARCHAR(254),
  ROLE_CLAIM_URI             VARCHAR(254),
  DESCRIPTION                VARCHAR(1024),
  DEFAULT_AUTHENTICATOR_NAME VARCHAR(254),
  DEFAULT_PRO_CONNECTOR_NAME VARCHAR(254),
  PROVISIONING_ROLE          VARCHAR(128),
  IS_FEDERATION_HUB          CHAR(1)      NOT NULL DEFAULT '0',
  IS_LOCAL_CLAIM_DIALECT     CHAR(1)      NOT NULL DEFAULT '0',
  DISPLAY_NAME               VARCHAR(255),
  IMAGE_URL                  VARCHAR(1024),
  UUID                       CHAR(36) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (TENANT_ID, NAME),
  UNIQUE (UUID)
);

-- IDP entry for FEDERATED idp for user session store tests.
INSERT INTO IDP (TENANT_ID,NAME,IS_ENABLED,IS_PRIMARY,HOME_REALM_ID,IMAGE,CERTIFICATE,ALIAS,INBOUND_PROV_ENABLED,INBOUND_PROV_USER_STORE_ID,USER_CLAIM_URI,ROLE_CLAIM_URI,DESCRIPTION,DEFAULT_AUTHENTICATOR_NAME,DEFAULT_PRO_CONNECTOR_NAME,PROVISIONING_ROLE,IS_FEDERATION_HUB,IS_LOCAL_CLAIM_DIALECT,DISPLAY_NAME,IMAGE_URL,UUID) VALUES
	 (-1234,'FEDERATED','1','1','localhost',NULL,0x5B5D,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,'9d0566d8-d919-483c-b49b-28c5e86e57f3');
